### ISSUE TITLE
 invalid selector after 0

### ISSUE THREAD

**Issue by nolafs** [sass/node-sass#1023]
Hi,

I keep getting the following error:

 invalid selector after 0

```css
 .\+\+#{$i} {
    @extend %grid-columns-all;
    margin-left: $grid-current-column-width;
  }
```

The version I am running are node-sass 3.0.0 > libsass  3.2.2

cheers
Olaf
