### ISSUE TITLE
Support foundation 5 (@include exports('grid') as example)

### ISSUE THREAD

**Issue by max107** [sass/node-sass#1076]
Constructions like `@include exports('grid')` not supported in 3.2.0, but correctly work in `0.9.5-rc1`.

Example code in foundation `_grid.scss`:

```scss
...
@include exports("grid") {
  @if $include-html-grid-classes {
    .row {
      @include grid-row;
...
```

exports mixin:

```scss
// IMPORT ONCE
// We use this to prevent styles from being loaded multiple times for compenents that rely on other components. 
$modules: () !default;
@mixin exports($name) {
  @if (index($modules, $name) == false) {
    $modules: append($modules, $name);
    @content;
  }
}
```

problem in `index($modules, $name) == false`

How to fix it?

**Comment by max107** [comment]
exports mixin:

```scss
// IMPORT ONCE
// We use this to prevent styles from being loaded multiple times for compenents that rely on other components. 
$modules: () !default;
@mixin exports($name) {
  @if (index($modules, $name) == false) {
    $modules: append($modules, $name);
    @content;
  }
}
```
