### ISSUE TITLE
Media queries not working properly with @extend

### ISSUE THREAD

**Issue by jgnewman** [sass/node-sass#110]
I have this:

``` scss
.size5 {
    font-size : 20px;
    @media screen and (max-height : 980px) {
        font-size : 18px;
    }
    @media screen and (max-height : 768px) {
        font-size : 16px;
    }
   @media screen and (max-width : 600px) {
        font-size : 15px;
    }
}
```

And this:

``` scss
.wrapper {
    header {
        span {
            @extend .size5;
        }
    }
}
```

Compiling to this:

``` css
.size5, .wrapper header span {
    font-size: 20px; }
    @media screen and (max-height: 980px) {
        .size5 {
            font-size: 18px; } }
    @media screen and (max-height: 768px) {
        .size5 {
            font-size: 16px; } }
    @media screen and (max-width: 600px) {
        .size5 {
            font-size: 15px; } }
```

Notice that `wrapper header span` is not inserted into the media queries.
