### ISSUE TITLE
the operation issure about the background-position

### ISSUE THREAD

**Issue by chenxiaochun** [sass/node-sass#1103]
```css
$num: 3;

.a{
	width: 100px;
	height: 100px;
	background-position: -10px*$num -120px;
}

.b{
	width: 100px;
	height: 100px;
	background-position: -20px*$num -120px;
}

.c{
	width: 100px;
	height: 100px;
	background-position: -30px*$num -120px;
}
```

```css
.a{width:100px;height:100px;background-position:-150px}
.b{width:100px;height:100px;background-position:-180px}
.c{width:100px;height:100px;background-position:-210px}
```
