### ISSUE TITLE
Selectors with inline comments do not get a new line

### ISSUE THREAD

**Issue by ntwb** [sass/node-sass#1139]
My setup on Mac OS X
```
$ ./node_modules/.bin/node-sass --version
node-sass	3.3.2	(Wrapper)	[JavaScript]
libsass  	3.2.5	(Sass Compiler)	[C/C++]
```

Example file `file.scss`:
```css
button,
html input[type="button"], /* 1 */
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button; /* 2 */
  cursor: pointer; /* 3 */
}
```

Running `./node_modules/.bin/node-sass file.scss`

Actual result:
```css
button,
html input[type="button"], input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button;
  /* 2 */
  cursor: pointer;
  /* 3 */ }
```

Expected result:
```css
button,
html input[type="button"], 
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button;
  /* 2 */
  cursor: pointer;
  /* 3 */ }
```

Using `sass` v3.4.18 directly results in the expected result `sass file.scss sass.css`
```css
button,
html input[type="button"],
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button;
  /* 2 */
  cursor: pointer;
  /* 3 */ }

/*# sourceMappingURL=sass.css.map */
```

The original fix I believe shipped with sass/libsass v3.2.0 here: https://github.com/sass/libsass/issues/1007

It was also originally raised here in https://github.com/sass/node-sass/issues/826

Any ideas on a fix, I've spend quite a bit of time just now trying fix and hacking through the toubleshooting.md file trying to get the tests running locally to no avail :(

**Comment by saper** [comment]
Good news:

Either the current libsass master I get:

```css
button,
html input[type="button"],
input[type="reset"],
input[type="submit"] {
  -webkit-appearance: button;
  /* 2 */
  cursor: pointer;
  /* 3 */ }

```

So this will be fixed with the next release of libsass and the node-sass release that follows.
