### ISSUE TITLE
Strange behavior while using @extend multiple times

### ISSUE THREAD

**Issue by NikFlip** [sass/node-sass#1314]
To avoid multiple lines of CSS, I'm using the foundations exports mixin (short description [here](http://4waisenkinder.de/blog/2014/03/06/import-once-in-sass-the-foundation-way/)).

But if I use @import to include my module multiple times, the @extend-functions blows up my css.
I also tried a @mixin instead of @extend and asserted that there is no problem.

Code does say more than thousand words, so I made a gist that shows the problem:
https://gist.github.com/NikFlip/5418438ef0da2dd1c694

Just run:
```
$ npm install
$ node .
```
and watch the result in the console

===

should:
```css
.selector-with-extend {
  background: red; }

.selector-without-extend {
  color: green; }
```

is:
```css
.selector-with-extend {
  background: red; }

.selector-without-extend {
  color: green; }

.selector-with-extend {
  background: red; }

.selector-with-extend {
  background: red; }

.selector-with-extend {
  background: red; }
```
