### ISSUE TITLE
error reading values after opacity

### ISSUE THREAD

**Issue by nissoh** [sass/node-sass#132]
``` scss
@mixin opacity($opacity) {
  opacity: $opacity;
  // IE8 filter
  filter: alpha(opacity = ($opacity * 100));
}
```

also fails at this mixin

``` scss
@mixin gradient-horizontal($startColor: #555, $endColor: #333) {
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#{ie-hex-str($startColor)}', endColorstr='#{ie-hex-str($endColor)}', GradientType=1); // IE9 and down
}
```

"error reading values after "gradient"
