### ISSUE TITLE
& closely after selector don't work

### ISSUE THREAD

**Issue by dchuangincar** [sass/node-sass#1324]
```css
.btn {
    .open& {
        color: #000;
    }
}
```
the code above just generate:
```css
.open& {
    color: #000;
}
```
but if there is a space before `&`, it's ok.
```css
.btn {
    .open &{
        color: #fff;
    }
}
```
the code above will generate:
```css
.open .btn {
  color: #fff; 
}
```
