### ISSUE TITLE
wrong additional debugging information in the output file as CSS comments

### ISSUE THREAD

**Issue by DarkPark** [sass/node-sass#1330]
code:

```js
sass.render({
    file: 'test.scss',
    data: 'body{background:blue; a{color:black;}}',
    sourceComments: true,
    outputStyle: 'expanded'
}, function(error, result) {
    console.log(result.css.toString());
});
```

gives this css:

```css
/* line 1, /home/dp/Projects/tests/spa-test/test.scss */
body {
  background: blue;
}

/* line 1, /home/dp/Projects/tests/spa-test/test.scss */
body a {
  color: black;
}
```

problem:

render option `data` shadowed option `file` so test.scss was ignored
which is fine, but in the comments this file should be ignored as well

expected output:

```css
/* line 1, stdin */
body {
  background: blue;
}

/* line 1, stdin */
body a {
  color: black;
}
```
