### ISSUE TITLE
unicode variables are formatted to UTF-8 during compilation

### ISSUE THREAD

**Issue by nicolaspanel** [sass/node-sass#1331]
__Issue__: unicode variables are formatted to UTF-8 during compilation
__Example__: `fa-glass` icon from [font-awesome](http://fortawesome.github.io/Font-Awesome/icon/glass/)
It is defined as :
```scss
.#{$fa-css-prefix}-glass:before { content: $fa-var-glass; } // see https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_icons.scss#L4) 
//  with 
$fa-var-glass: "\f000"; // see https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss#L304
```

// After compilation it becomes:
```css
.fa-glass:before{content:""} 
// instead of
.fa-glass:before{content:"\f000"}
```

__SSCCE__:
```js
> var sass = require('node-sass');
> console.log(sass.renderSync({data: '$fa-var-glass: "\\f000"; .fa-glass:before { content: $fa-var-glass; }'}).css.toString())
@charset "UTF-8";
.fa-glass:before {
  content: ""; }

```

__Versions__:
 * node: v4.2.4
 * node-sass: v3.4.2
 * font-awesome: v4.5.0

**Comment by xzyfer** [comment]
Please do not post code that does not compile. We will not dig through your framework to figure what's going.

I'll assume you meant the following.

```scss
$fa-var-glass: "\f000";
foo {
  content: $fa-var-glass;
```

In which case both node-sass and Ruby Sass output

```css
@charset "UTF-8";
.glass:before {
  content: "";
}
```

It might not look pretty but it's perfectly valid CSS. Since we're doing what Ruby Sass does this is not a bug.

**Comment by nicolaspanel** [comment]
Thank you for the answer but the generated CSS should be :
```css
.glass:before {
  content: "\f000"; // not ""
}
```
Seems to be a [https://github.com/sass/libsass](libsass) bug then...
