### ISSUE TITLE
Variable in calc() fails to interpolate

### ISSUE THREAD

**Issue by bcherny** [sass/node-sass#1341]
```scss
// ok
element {
  height: calc(100% - 50px)
}
/* =>
element {
  height: calc(100% - 50px)
}
*/

// fails to interpolate! $a appears in the compiled output
$a: 50px
element {
  height: calc(100% - $a)
}
/* =>
element {
  height: calc(100% - $a)
}
*/
```
