### ISSUE TITLE
The variable yellow is not converted when using the minified output style

### ISSUE THREAD

**Issue by harianus** [sass/node-sass#1351]
I have this *scss*-code:

```scss
$colors: (purple: #7B81CB, yellow: #FEC051);

@each $color-name in map-keys($colors) {
  $color-text: map-get($colors, $color-name);

  .color.#{$color-name} {
    color: $color-text;
  }
}
```

When I run `node-sass app.scss app.css`, I get this **(as expected)**:

```css
.color.purple {
  color: #7B81CB; }

.color.yellow {
  color: #FEC051; }
```

But when I run `node-sass --output-style compressed app.scss app.css`, I get this **(not expected)**:

```css
.color.purple{color:#7B81CB}
```

This is what I am expecting:

```css
.color.purple{color:#7B81CB}.color.yellow{color:#FEC051}
```

I solved this problem in my app by changing `yellow` to `yellows`.

* * * 

I also tested it in *[sassc](https://github.com/sass/sassc)* and there it works, this is the current *node-sass* version:

```
$ node-sass --version
node-sass	3.4.2	(Wrapper)	[JavaScript]
libsass  	3.3.2	(Sass Compiler)	[C/C++]
```

OS: *Mac OS X 10.11.2*
