### ISSUE TITLE
Interpolation with parent reference is not working

### ISSUE THREAD

**Issue by niksy** [sass/node-sass#1365]
Input Sass:

```scss
$bar: 'bar';

.foo {

	&--#{$bar} {
		color:red;
	}
}
```

Should give output CSS:

```css
.foo--bar {
	color:red;
}
```

Thrown error is:

```sh
{
  "formatted": "Error: Invalid CSS after \".foo {\": expected \"}\", was \"&--$bar {\"\n        on line 13 of input/index.scss\n>> .foo {\n   ------^\n",
  "message": "Invalid CSS after \".foo {\": expected \"}\", was \"&--$bar {\"",
  "column": 7,
  "line": 13,
  "file": "/Users/niksy/Projects/node-sass-test/input/index.scss",
  "status": 1
}
```

Ruby version of Sass is OK.
Using this without parent reference selector also works OK.

Possibly related to https://github.com/sass/libsass/issues/1825?
