### ISSUE TITLE
Different compiling outputs (may be related to OS)

### ISSUE THREAD

**Issue by allenfantasy** [sass/node-sass#1383]
Hi, here I met some really interesting situation when working with my colleagues using [`gulp-sass`](https://github.com/dlmanning/gulp-sass).

Since `node-sass` serves as `gulp-sass`'s dependency so I think this issue may be more likely better to put it here, because `gulp-sass` only cares about the task running IMO.

As background information - my colleague is using Windows 10 / node 0.12.7, while I am using Mac OS X El Capitan / node 0.12.4.

We have some scss file code like this :

```scss
.msg,
.text {
  font: 16px/24px 'Microsoft Yahei','Helvetica Neue',Helvetica,Arial,sans-serif;
}
```

We use gulp as task runner so we're using `gulp-sass`. We found our compiled css would be a little different ( I capture this from my git diff ):

```css
/* my colleague's output */
.msg,
.text {
  font: 16px/24px "Microsoft Yahei", "Helvetica Neue", Helvetica, Arial, sans-serif;
}

/* my output */
.msg, .text {
  font: 16px/24px 'Microsoft Yahei','Helvetica Neue',Helvetica,Arial,sans-serif; 
}
```

Noticed that there are 3 difference between our outputs:

1. the selector ( 2 lines vs. 1 line );
2. the quote mark ( double quote mark vs. single quote mark );
3. there is a `space after the comma` in my colleague's output.

We double-checked the following fact:

* the source scss code is 100% identical
* we are using the same version of `gulp-sass` ( so `node-sass`'s version is the same )

Any tips or ideas?

UPDATE: I've updated the node version to `0.12.7` which is the same with my colleague's. But it doesn't help.
