### ISSUE TITLE
sourceComments - normal vs map

### ISSUE THREAD

**Issue by sindresorhus** [sass/node-sass#141]
What's the difference between them? Can you make that clearer in the readme?

Also, both values output the same thing:

``` css
/* line 1, /Users/sindresorhus/Projects/grunt-sass/test/fixtures/imported */
li {
  font-family: serif;
  font-weight: bold;
  font-size: 1.2em; }

/* line 6, /Users/sindresorhus/Projects/grunt-sass/test/fixtures/test.scss */
.content-navigation {
  border-color: #3bbfce;
  color: #2ca2af; }

/* line 12, /Users/sindresorhus/Projects/grunt-sass/test/fixtures/test.scss */
.border {
  padding: 8px;
  margin: 8px;
  border-color: #3bbfce; }
```
