### ISSUE TITLE
compressed does not remove last colon for properties

### ISSUE THREAD

**Issue by james2doyle** [sass/node-sass#142]
I was doing some testing of ruby sass vs. node-sass. I was testing the compilation time of each one and added the `compress` flag to each command.

I noticed that the node-sass didn't remove the last, unnecessary, colon when compression is on.
#### source input

``` css
$bodyColor: #66ccff;
$bodyBackground: #212121;
body {
  background: $bodyBackground;
  color: $bodyColor;
  header {
    max-width: 100%;
    height: 100px;
    & > nav {
      display: inline-block;
      ul {
        margin: 0;
        padding: 0;
      }
    }
  }
}
```
#### sass output

command: `sass --style compressed --scss test.scss test-rb.css`

``` css
body{background:#212121;color:#6cf}body header{max-width:100%;height:100px}body header>nav{display:inline-block}body header>nav ul{margin:0;padding:0}
```
#### node-sass output

command: `time node-sass --output-style="compressed" test.scss test-node.css`

``` css
body {background:#212121;color:#66ccff;}body header {max-width:100%;height:100px;}body header>nav {display:inline-block;}body header > nav ul {margin:0;padding:0;}
```

There are 13 additional characters in the node-sass output. This isn't much on a 17 line file, but it will grow exponentially over larger files.

I will add this issue to libsass as well.
