### ISSUE TITLE
Not able to build getting error on sass compilation 

### ISSUE THREAD

**Issue by jesudasjj** [sass/node-sass#1460]
Hi,
After updating with the latest node-sass 3.5.0
We are getting this error and breaking the build

failed to @extend ".class".
>> The selector ".class" was not found.
>> Use "@extend .class!optional" if the extend should be able to fail.

I know, you guys are released latest version 3.5.1, same result.

Let me know, its happening for you guys ?

**Comment by mdshaheer** [comment]
I am also getting the same issue with the recent build.

**Comment by xzyfer** [comment]
Please provide a copy/pastable snippet of code that produces this error. Without this we simply cannot help.

**Comment by mdshaheer** [comment]
.class--name {
  @extend .title;
}
This is what we are doing and it was working till the latest update to 3.5.1. May be we are doing something wrong but any kind of help is really appreciable

**Comment by xzyfer** [comment]
@mdshaheer your code does not compile. Please provide a **fully** working sample I can copy and paste. I suggest using http://www.sassmeister.com/

**Comment by mdshaheer** [comment]
.title {
  color: #ccc;
  padding: 0;
  a {
    color: #ccc;
    text-decoration: underline;
    &:focus {
      color: #000;
      text-decoration: none;
      border-bottom: 1px dotted #000;
    }
  }
}

.class--name {
  @extend .title;
}

**Comment by xzyfer** [comment]
I do not see your error, this code compiles to 

```css
.title, .class--name {
  color: #ccc;
  padding: 0; }
  .title a, .class--name a {
    color: #ccc;
    text-decoration: underline; }
    .title a:focus, .class--name a:focus {
      color: #000;
      text-decoration: none;
      border-bottom: 1px dotted #000; }
```

Please provide the output of

```
npm ls node-sass
```
