### ISSUE TITLE
using &, nest and adjacent sibling selector may make bugs

### ISSUE THREAD

**Issue by marzk** [sass/node-sass#1481]
```scss
// Before
.parent {
  .adjacent {
    &-left+&-right {
      margin: 0;
    }
  }
  .adjacent-left+.adjacent-right {
    margin: 0;
  }
}
```
Compiled:
```css
/* After */
/* Error, it will never fit */
.parent .adjacent-left + .parent .adjacent-right {
  margin: 0;
}
/* Correct */
.parent .adjacent-left + .adjacent-right {
  margin: 0;
}
```

u could try this on [sassmeister](http://www.sassmeister.com/).

**Comment by xzyfer** [comment]
@marzk I'm not sure I understand. The output looks correct to me.


```sass
.parent {
  .adjacent {
    &-left+&-right {
      margin: 0;
    }
  }
  .adjacent-left+.adjacent-right {
    margin: 0;
  }
}
```
Ruby Sass 3.4.21
```css
.parent .adjacent-left + .parent .adjacent-right {
  margin: 0; }
.parent .adjacent-left + .adjacent-right {
  margin: 0; }
```
Node Sass v3.6.0
```css
.parent .adjacent-left + .parent .adjacent-right {
  margin: 0; }

.parent .adjacent-left + .adjacent-right {
  margin: 0; }
```
