### ISSUE TITLE
@at-root with #{&} inside a comma-separated selector generates wrong code

### ISSUE THREAD

**Issue by cH40z-Lord** [sass/node-sass#1549]
**Tested versions**: v3.7 and v3.4

Given the following input:

```css
.class-a {
    .class-b,
    .class-c {
        color: yellow;

        @at-root .something-at-root#{&} {
            color: pink;
        }
    }
}
```

You'll get the following output:

```css
.class-a .class-b,
.class-a .class-c {
    color: yellow;
}

.something-at-root.class-a .class-b,
.class-a .class-c {
    color: pink;
}
```

The problem here is that `#{&}`, which I used here in this example to prepend some selector (`.something-at-root`) right at the beginning, which causes the compiler to generate wrong output.

I'd expect the following output for the second block:

```css
.class-a .class-b,
.class-a .class-c {
    color: yellow;
}

.something-at-root.class-a .class-b,
.something-at-root.class-a .class-c {
    color: pink;
}
```
