### ISSUE TITLE
"invalid property name" error but only seems to affect older Node versions

### ISSUE THREAD

**Issue by Jevonius** [sass/node-sass#1556]
Hi, I've been trying to diagnose a problem with one of our SASS files and have narrowed it down to a difference in the node-sass-binaries.

Summary of the issue:
An SCSS file as follows:
``` scss
$btn-background   : (
  'primary'       : '#8DC9A0',
  'highlight'     : '#ffffff'
);

.button {
  @each $key, $value in $btn-background {
    &.-#{$key} {
      border: none;
      text-transform: uppercase;
      color: #{$value}
    }
  }
}
```
Fails with the error:
``` json
{
  "message": "invalid property name",
  "column": 41,
  "line": 7,
  "file": "C:/Temp/mysass.scss",
  "status": 1
}
```
It compiles perfectly fine with the latest versions of Ruby Sass, SassC and 2 out of 3 variants of node-sass 3.7.0 I've tried. The binaries that I've tested (all from https://github.com/sass/node-sass-binaries/commit/eaa4e80ab5507602b9ced4e59396b6c40b4cacb4) are:
win32-x64-46 - works
win32-ia32-46 - works
win32-ia32-14 - fails

Further details of the issue are here (I originally thought the bug was with WebCompiler): https://github.com/madskristensen/WebCompiler/issues/208

The same code worked perfectly in node-sass 3.4.2 but something seems to have changed since then.

I do have a workaround, but would be great if I didn't have to use it! :)

Thanks.
