### ISSUE TITLE
Including mixin in itself produces no output, no error

### ISSUE THREAD

**Issue by mattdistefano** [sass/node-sass#1582]
Not sure if this is a node-sass or libsass issue but...

The following code just causes the process to exit without error or output (using the CLI and gulp-sass):

```scss
@mixin my-mixin() {
    @include my-mixin();
}

.foo {
    display: block;
}

@include my-mixin();
```
Obviously I don't expect this to actually compile, but it seems like there should be an error emitted at least.

node 5.8.0 on Windows 10
node-sass       3.7.0   (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]
