### ISSUE TITLE
Can't import without extension

### ISSUE THREAD

**Issue by sindresorhus** [sass/node-sass#16]
Trying to @import a file fails if the extension is not specified:

> ERROR -- , line 1: error reading file "test"

From the sass [docs](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#import):

> For example,
> 
> @import "foo.scss";
> or
> 
> @import "foo";
## 

This works:

``` scss
var sass = require('node-sass');
sass.render('@import "test.scss";body{background:blue; a{color:black;}}', function(err, css){
    console.error(err);
    console.log(css)
});
```

This does not:

``` scss
var sass = require('node-sass');
sass.render('@import "test";body{background:blue; a{color:black;}}', function(err, css){
    console.error(err);
    console.log(css)
});
```
