### ISSUE TITLE
Inconsistent extended syntax inside media queries

### ISSUE THREAD

**Issue by battaglr** [sass/node-sass#1610]
When using the extended syntax, I get inconsistent rule separation inside and outside media queries.

*Input:*

```sass
.Test-1 {
  color: black;
}

.Test-2 {
  color: white;
}

@media screen {
  .Test-1 {
    color: black;
  }

  .Test-2 {
    color: white;
  }
}
```

*Output:*

```css
.Test-1 {
  color: black;
}

.Test-2 {
  color: white;
}

@media screen {
  .Test-1 {
    color: black;
  }
  .Test-2 {
    color: white;
  }
}
```

*Expected:*

```css
.Test-1 {
  color: black;
}

.Test-2 {
  color: white;
}

@media screen {
  .Test-1 {
    color: black;
  }

  .Test-2 {
    color: white;
  }
}
```

I'm using v3.8.0 and the CLI to compile: `node-sass --output-style expanded input.scss output.css`.

I know this is just a style thing, but it was not the output I expected.
