### ISSUE TITLE
postCSS definitions issue in sass

### ISSUE THREAD

**Issue by alisamar** [sass/node-sass#1624]
I am having strange issue when I test the postCSS with Sass!

HTML color names converted to the hex code!

```scss
// SASS
:root {
  --teal: #444; // postCSS variable
}

div.1 { content: var(--teal) } // postCSS definition
div.2 { content: (- red) }
div.3 { content: (+- blue) }
div.4 { content: (-green) }
div.5 { content: (+ yellow) }
```

```css
/* CSS OUTPUT */
:root {
  --teal: #444; }

div.1 {
  content: var(--#008080); }
div.2 {
  content: -#ff0000; }
div.3 {
  content: +-#0000ff; }
div.4 {
  content: -#008000; }
div.5 {
  content: +#ffff00; }
```
so I can not use color names as variable in postCSS with sass :(
