### ISSUE TITLE
Unexpected output from 'compressed' option

### ISSUE THREAD

**Issue by noahgrant** [sass/node-sass#1654]
`node-sass v3.8` (via `gulp-sass v2.3.2`):

We just upgraded to node 6 and to node-sass v3.8, and under the `nested` or `compact` `outputStyle` options, everything appears correct.  But we have this block:

```scss
  .my-container {
    $colors: (
      (name: blue, color: $blue, background: $blue-bkgrd),
      (name: green, color: $green, background: $green-bkgrd),
      (name: orange, color: $orange, background: $orange-bkgrd),
      (name: yellow, color: $yellow, background: $yellow-bkgrd)
    );

    @each $color in $colors {
      &.#{map-get($color, name)} {
        h3 {
          color: map-get($color, color);
        }

        .some-class {
          background: map-get($color, background);

          em {
            color: map-get($color, color);
          }
        }
      }

      &:hover {
        &.#{map-get($color, name)} {
          h3 {
            color: darken(map-get($color, color), 5%);
          }
        }
      }
    }
  }
```

and in the `compressed` output (which is what we push to production), we are getting this unexpected output:

```css
// ...
.my-container:hover.orange h3{color:(<darker orange>)}h3{color:(<darker orange>)}.some-class{background:(<orange bkgrd>)}.some-class em{color:(<orange>)}h3{color:(<orange>)}
// ...
```

which is putting `h3` rules and `.some-class` rules in the global scope instead of being nested within `.my-container`.

It seems possible that some mapping and/or nesting syntax has changed in our upgrade from libsass 3.1.0 to libsass 3.3.6, but either way, I would expect the same css output in the `compressed` style as with the `nested`.
