### ISSUE TITLE
Interpolation in @error not working as docs suggest

### ISSUE THREAD

**Issue by mkstix6** [sass/node-sass#1752]
This example of `@error` in the sass_lang docs isn't working as expected. Interpolating the variables in the `@error` strings seems broken (http://sass-lang.com/documentation/file.SASS_REFERENCE.html#_7).
Works fine in sassmeister.
Also the interpolation works fine for `@warn`.

```scss
@mixin adjust-location($x, $y) {
    @if unitless($x) {
        @error "$x may not be unitless, was #{$x}.";
    }

    @if unitless($y) {
        @error "$y may not be unitless, was #{$y}.";
    }

    position: relative;
    left: $x;
    top: $y;
}

p {
    @include adjust-location(4, 5);
}
```

Doesn't interpolate the variables in the `@error` strings. Producing this in terminal:
```terminal
Message:
    style.scss
Error: $x may not be unitless, was 4.
        on line 76 of style.scss
>>         @error "$x may not be unitless, was #{$x}.";
   --------^
```

When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`):
3.8.6

- Node version (`node -v`):
v5.1.0

- Node Process (`node -p process.versions`):
{ http_parser: '2.6.0',
  node: '5.1.0',
  v8: '4.6.85.31',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '47',
  openssl: '1.0.2d' }

- Node Platform (`node -p process.platform`):
darwin

- Node architecture (`node -p process.arch`):
x64

- node-sass version (`node -p "require('node-sass').info"`):
node-sass	3.10.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]

- npm node-sass versions (`npm ls node-sass`):
planit@1.0.0 /Users/mk/Sites/planit
└─┬ gulp-sass@2.3.2
  └── node-sass@3.10.1
