### ISSUE TITLE
node-sass trips over old-IE opacity CSS

### ISSUE THREAD

**Issue by TomGault** [sass/node-sass#189]
I pasted this example from http://www.quirksmode.org/css/opacity.html into a file named test.scss:

``` css
.test {
  background-color: #6374AB;
  width: 100%;
  color: #ffffff;
}

.opaque1 {  // for all other browsers
  opacity: .5;
}

.opaque2 {  // for IE5-7
  /* Comment out the following and the file compiles no problem. */
  filter: alpha(opacity=50);
}

.opaque3 {  // for IE8
  -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
}
```

I used this test harness:

``` javascript
var sass = require('node-sass');
sass.render({
    file: 'test.scss',
    success: function (css) {
      console.log('Done!');
      console.log(css);
    },
    error: function (error) {
      console.log(error);
    }
});
```

Result:
`.../test.scss:13: error: error reading values after opacity`
