### ISSUE TITLE
[sourceComments] doesn't work

### ISSUE THREAD

**Issue by wzup** [sass/node-sass#2056]
Doesn't delete comments in final `.css` bundle. All comments are preserved. Why?

Settings in Webpack 2. 

```js
    {
        loader: 'sass-loader',
        options: {
            sourceComments: true
        }
    }
```
Source file. And that comment is preserved.
```scss
/**
 * This is a comment I want to be removed in final .css bundle
 */
.foo {
    color: red;
}
```
