### ISSUE TITLE
Using @extend breaks invalid pseudo classes

### ISSUE THREAD

**Issue by ofagbemi** [sass/node-sass#2057]
This might be more of a libsass issue, but the handling of different cases makes that a little ambiguous.

Here's a gist that repros the issue: https://gist.github.com/ofagbemi/80bce63646b33ed2ee6f801f8f78b47d

I'm using [css-modules](https://github.com/css-modules/css-modules) which introduces a `:global` flag. Running code with the `:global` flag through `node-sass` looks fine, even though doing so results in an error at https://www.sassmeister.com/. In addition, `:global` can be used with other pseudo-classes, e.g.

```scss
.greeting {
  color: orange;
}

:not(:global(.hello)) {
  color: red;
}
```
The output is:
```css
.greeting {
  color: orange;
}

:not(:global(.hello)) {
  color: red;
}
```
This output works perfectly in my case — this is passed through our toolchain to [`css-loader`](https://github.com/webpack-contrib/css-loader), which can interpret the `:global` flag.

However, an issue arises when the `:global` flag is used with another pseudo-class, e.g. `:not(:global(.hello))` _and_ the `@extend` command is used in the code. In this case, the entire selector gets dropped from the output. E.g.

```scss
.greeting {
  color: orange;
}

.good-morning {
  @extend .greeting;
}

:not(:global(.hello)) {
  color: red;
}
```
The output is:
```css
.greeting, .good-morning {
  color: orange;
}

{
  color: red;
}
```

Note that the `:not(:global(.hello))` selector has disappeared.

This is a compilation issue, so I wasn't sure if here or libsass was the best place to report this. However, since the output I expected (with invalid pseudo-classes left intact) actually yields a sass error, I assumed this was an issue with the way `node-sass` handles those errors.

Thanks!

NPM version: `4.2.0`
Yarn version: `0.19.1`
Node version: `7.8.0`
Node Process: 
```
{ http_parser: '2.7.0',
  node: '7.8.0',
  v8: '5.5.372.43',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }
```
Node Platform: `darwin`
Node architecture: `x64`
node-sass version:
```
node-sass	4.5.3	(Wrapper)	[JavaScript]
libsass  	3.5.0.beta.2	(Sass Compiler)	[C/C++]
```
npm node-sass versions: `node-sass@4.5.3`
