### ISSUE TITLE
Pass in `data` with a source map?

### ISSUE THREAD

**Issue by jbsulli** [sass/node-sass#2058]
When reporting an bug, **you must provide this information**:

- NPM version (`npm -v`): 3.10.10
- Node version (`node -v`): v6.10.3
- Node Process (`node -p process.versions`): {
  http_parser: '2.7.0', node: '6.10.3',
  v8: '5.1.281.101',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
- Node Platform (`node -p process.platform`): win32
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
node-sass       4.5.3   (Wrapper)       [JavaScript]
libsass         3.5.0.beta.2    (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`): 4.5.3

Is node-sass supposed to support an embedded source map? I tried the passing the following:
```scss
$background: #000;
body {
    background:$background;
}


/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInRlc3QvdmFycy5tZCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFJQTtBQUlBO0FBQ0E7QUFDQSIsImZpbGUiOiJzdHlsZXMuc2NzcyJ9 */
```

The embedded source map seems to just be ignored.
