### ISSUE TITLE
Prettify output CSS (with --output-style=expanded)

### ISSUE THREAD

**Issue by am11** [sass/node-sass#208]
With `--output-style=expanded`, please generate the CSS in a properly expanded and well-formatted way.

**Current:**

``` CSS
/* line 65, C:\Users\Adeel\Documents\Visual Studio 2013\WebSites\WebSite1\1\2\3\cd.scss */
h6 {
  font-family: "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif;
  font-size: 12px; }

/* line 71, C:\Users\Adeel\Documents\Visual Studio 2013\WebSites\WebSite1\1\2\3\cd.scss */
#main-nav {
  background: url('menu_background.png') repeat-x;
  min-height: 45px;
  margin-bottom: 60px; }
  /* line 76, C:\Users\Adeel\Documents\Visual Studio 2013\WebSites\WebSite1\1\2\3\cd.scss */
  #main-nav .top-bar {
    margin: 0 auto;
    background-color: transparent; }
```

**Desired:**

``` CSS
/* line 65, C:\Users\Adeel\Documents\Visual Studio 2013\WebSites\WebSite1\1\2\3\cd.scss */
h6
{
    font-family: "Segoe UI", Frutiger, "Frutiger Linotype", "Dejavu Sans", "Helvetica Neue", Arial, sans-serif;
    font-size: 12px;
}

/* line 71, C:\Users\Adeel\Documents\Visual Studio 2013\WebSites\WebSite1\1\2\3\cd.scss */
#main-nav
{
    background: url('menu_background.png') repeat-x;
    min-height: 45px;
    margin-bottom: 60px;
}

    /* line 76, C:\Users\Adeel\Documents\Visual Studio 2013\WebSites\WebSite1\1\2\3\cd.scss */
    #main-nav .top-bar
    {
        margin: 0 auto;
        background-color: transparent;
    }
```

Note, after each rule there is a line-break, curly braces are on separate lines and nested rules are following desired indentation spacing (4 in this case, perhaps with another switch `--indent`).

Incidentally, `nested` and `expanded` (and I guess `compact` as well), all generates same kind of output. What is the difference?

Thanks.
