### ISSUE TITLE
Doesn't work in Node 0.8.x

### ISSUE THREAD

**Issue by sindresorhus** [sass/node-sass#21]
Testcase:

``` js
var sass = require('node-sass');
sass.render('body{background:blue; a{color:black;}}', function(err, css){
  console.log(css)
});
```

In Node 0.6.x:

``` css
body {
  background: blue;
}
body a {
    color: black;
}
```

In Node 0.8.x it never finishes...
