### ISSUE TITLE
Deep nesting with a variable causes build fail

### ISSUE THREAD

**Issue by subhaze** [sass/node-sass#2122]
This ticket was initially filed at: https://github.com/webpack-contrib/sass-loader/issues/502

**npm**: 5.3.0
**node** 8.4.0
**process.versions**
  - http_parser: '2.7.0',
  - node: '8.4.0',
  - v8: '6.0.286.52',
  - uv: '1.13.1',
  - zlib: '1.2.11',
  - ares: '1.10.1-DEV',
  - modules: '57',
  - nghttp2: '1.22.0',
  - openssl: '1.0.2l',
  - icu: '59.1',
  - unicode: '9.0',
  - cldr: '31.0.1',
  - tz: '2017b'

**process.platform** linux
**process.arch** x64
**sass-loader** 6.0.6

Using `sass-loader` I ran into an issue where builds would fail when using variables that were deeply nested, though, I'm not sure if this is specifically a sass-loader or libsass issue.

I pulled the code and modified https://github.com/webpack-contrib/sass-loader/blob/master/lib/loader.js#L15 to use the `sass.renderSync` function which appears to remedy the issue.

While this is a compilation error, I'm filing here since `sass.renderSync` does appear to work.

The minimal amount of breaking code I've come up with is the following:

fails
```scss
$testing: #ff00ff;
body{
  div{
    div{
      div{
        div{
          div{
            div{
              div{
                div{
                  div{
                    div{
                      div{
                        &.a-class{
                          span{
                            color: $testing;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Yeah... lots of nesting... but when a variable is used at that level webpack fails to build.

However, if you comment out one of the divs, OR, if you use the color `#ff00ff` directly the build does not fail.

works
```scss
$testing: #ff00ff;
body{
  div{
    div{
      div{
        div{
          div{
            div{
              div{
                div{
                  div{
                    div{
                      // div{
                        &.a-class{
                          span{
                            color: $testing;
                          }
                        }
                      // }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

works
```scss
$testing: #ff00ff;
body{
  div{
    div{
      div{
        div{
          div{
            div{
              div{
                div{
                  div{
                    div{
                      div{
                        &.a-class{
                          span{
                            color: #ff00ff;
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
