### ISSUE TITLE
Calc() - Negative signs not inverting signs in parenthesis

### ISSUE THREAD

**Issue by McBenny** [sass/node-sass#2292]
Hi,
I have a scss declaration with:
`height: calc(100vh - (50px + 2rem));`

The idea is that I want to substract 50px + 2rem from 100vh. I know I could get rid of the internal parenthesis, but for the sake of understanding the formula, I prefer to keep them.

So the intended calculation according to the rule should be equal to:
`height: calc(100vh - 50px - 2rem);`

But I get:
`height: calc(100vh - 50px + 2rem);`

=> The minus sign doesn't invert the signs in the parenthesis. Or maybe the parenthesis are just stripped.

According to what I understand, it shouldn't happen. Any idea?

I use node-sass@^3.4.2 in my webpack config, in a React project.

**Comment by xzyfer** [comment]
Can you explicitly install node-sass@beta?

**Comment by McBenny** [comment]
Hi @xzyfer ,
I tried with `"_from": "node-sass@beta",  "_id": "node-sass@4.4.0"`, the result is exactly the same.

I've done a bit of testing, I think there is a "pattern": 3 or more different units cause a problem.

**OK** | `calc(100px - (50px + 10px)` => `40px`
**OK** | `calc(100vh - (50px + 10px)` => `calc(100vh - 60px)`
**OK** | `calc(100px - (50vh + 10px)` => `calc(90px - 50vh)`
**OK** | `calc(100px - (5rem + 10px)` => `calc(90px - 5rem)`
**OK** | `calc(100vh - (5vh + 10px)` => `calc(95vh - 10px)`
**OK** | `calc(100rem - (10px + 5rem)` => `calc(95rem - 10px)`

**KO** | `calc(100vh - (5rem + 10px)` => `calc(100vh - 5rem + 10px)`
**KO** | `calc(100vh - (10px - 5rem)` => `calc(100vh - 10px + 5rem)`
**KO** | `calc(100% - (5rem + 10px)` => `calc(100% - 5rem + 10px)`
**KO** | `calc(100% - (5vh + 10px)` => `calc(100% - 5vh + 10px)`
**KO** | `calc(100rem - (5vh + 10px)` => `calc(100rem - 5vh + 10px)`
**KO** | `calc(100rem - (5% + 10px)` => `calc(100rem - 5% + 10px)`
**KO** | `calc(100vh - (5% + 10px)` => `calc(100vh - 5% + 10px)`

**KO** | `calc(100vh - (5% + 10px - 2rem)` => `calc(100vh - 5% + 10px - 2rem)`

Hope this helps.

**Comment by McBenny** [comment]
Any news @xzyfer ?

**Comment by xzyfer** [comment]
Having re-read this issue I can say the behaviour is intended. CSS math follows the rules of mathematical ordering (BODMAS).

**Comment by McBenny** [comment]
Sorry, @xzyfer , maybe I'm a little stupid but whatever the rule the calculation is following, the examples I gave show an inconsistency. With 2 different units, the + sign is inverted, with 3 different units, the + sign is not inverted.

```calc(100vh - (5vh + 10px))``` gives: ```calc(95vh - 10px)```
So the + sign in the brackets is inverted, right?

and when I write this (I only changed the units):
```calc(100vh - (5% + 10px))``` I get: ```calc(100vh - 5% + 10px)```
So the + sign in the brackets is NOT inverted.

Does that mean that we invert this + sign only if we have 2 different units max?

I wrote a small test in [CodePen](https://codepen.io/mcbenny/pen/bvpaMP) and the same in [jsFiddle](https://jsfiddle.net/6gb4Lrnj/)
You can see the initial calc formula, the formula without the brackets, and the formula without the brackets AND the sign inverted.

Please tell me where I'm wrong.

**Comment by xzyfer** [comment]
node-sass@beta is old. Try the latest 4.8.3 release.

**Comment by xzyfer** [comment]
Input
```scss
a {
  b: calc(100px - (50px + 10px));
  c: calc(100vh - (50px + 10px));
  d: calc(100px - (50vh + 10px));
  e: calc(100px - (5rem + 10px));
  f: calc(100vh - (5vh + 10px));
  g: calc(100rem - (10px + 5rem));

  h: calc(100vh - (5rem + 10px));
  i: calc(100vh - (10px - 5rem));
  j: calc(100% - (5rem + 10px));
  k: calc(100% - (5vh + 10px));
  l: calc(100rem - (5vh + 10px));
  m: calc(100rem - (5% + 10px));
  n: calc(100vh - (5% + 10px));

  o: calc(100vh - (5% + 10px - 2rem));
}
```
Output
```css
a {
  b: calc(100px - (50px + 10px));
  b: calc(100vh - (50px + 10px));
  b: calc(100px - (50vh + 10px));
  b: calc(100px - (5rem + 10px));
  b: calc(100vh - (5vh + 10px));
  b: calc(100rem - (10px + 5rem));
  b: calc(100vh - (5rem + 10px));
  b: calc(100vh - (10px - 5rem));
  b: calc(100% - (5rem + 10px));
  b: calc(100% - (5vh + 10px));
  b: calc(100rem - (5vh + 10px));
  b: calc(100rem - (5% + 10px));
  b: calc(100vh - (5% + 10px));
  b: calc(100vh - (5% + 10px - 2rem));
}
```
