### ISSUE TITLE
CSS variables are not compiled correctly

### ISSUE THREAD

**Issue by vugar005** [sass/node-sass#2358]
Hi. In angular application where I use node-sass ,css variables are not compiled correctly.
I tested same html template and css sheets in jsfiddle. [https://jsfiddle.net/Vugar005/zza6624e/2/](https://jsfiddle.net/Vugar005/zza6624e/2/)
it works there but node-sass seems does not compile correctly. What might be problem?
Thanks!
```
- NPM version : 5.5.1
- Node version : 8.9.1:
- Node Process : 
{ http_parser: '2.7.0',
  node: '8.9.0',
  v8: '6.1.534.46',
  uv: '1.15.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '59.1',
  unicode: '9.0',
  cldr: '31.0.1',
  tz: '2017b' }
- Node Platform: win32:
- Node architecture: x64:
- node-sass version (`node -p "require('node-sass').info"`): 
node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions (`npm ls node-sass`): `-- (empty)
```

**Comment by xzyfer** [comment]
Please search issues before opening a new one. Your questions have already
been answered.

**Comment by vugar005** [comment]
@xzyfer  Could you please at least mention that questions. I searched and did not find closed issues helpful.

**Comment by xzyfer** [comment]
Please define "not compile correctly". I'm not going to read and try to understand your hundreds of lines of code.

A simple < 10 line example of your input, the expected output, and the real output is required.

**Comment by vugar005** [comment]
@xzyfer  . I simplified and added code to [stackblitz](https://stackblitz.com/edit/angular-swpjwt?file=app%2Fapp.component.scss)  <br>
Problem is variables from :root are not applied. But when I rename :root => .component. It works as expected. The box is shown. Why :root variables are not taken?
Thanks in advance!

**Comment by xzyfer** [comment]
Please just provide the input css, expected output, and actual output here.

**Comment by vugar005** [comment]
@xzyfer . When I compile with node-sass the output file is as expected. But when run in browser, :root values are not assigned to elements. Can you please check stackblitz and tell what is wrong ?

**Comment by vugar005** [comment]
@xzyfer I move :root to global style.css and it works as expected. It causes problem within component.
What might be issue?

**Comment by tornography** [comment]
Same problem here. Here are the examples and current/expexted outputs. Expected output seems to work up to v4.7.2. At least that's the fallback we use.

Input:
```scss
$color: #f1f3f6;

:root {
    --color-not-working: $color;
}

.class {
    color: $color;
}
```

Output:
```scss
:root {
  --color-not-working: $color;
}

.class {
  color: #f1f3f6;
}
```

Expected:
```scss
:root {
  --color-not-working: #f1f3f6;
}

.class {
  color: #f1f3f6;
}
```

What does work:
```scss
$color: #f1f3f6;

:root {
    --color-not-working: #{$color};
}

.class {
    color: $color;
}
```
