### ISSUE TITLE
problems with nested styles with @extend directive 

### ISSUE THREAD

**Issue by davidnieto** [sass/node-sass#238]
When I try use @extend directive in my project, it doesn`t work correctly.

This is my scss code:

``` scss
.myNav {
  color: blue;
  > li {
    color: red;
  }
}

.myMenu {
  @extend .myNav;
}
```

This is the compilated css I get with node-sass:

``` css
.myNav, .myMenu { color: blue; }
```

And when I compile the same code with Ruby, I get this one:.

``` css
.myNav, .myMenu { color: blue; }
.myNav > li, .myMenu > li { color: red; }
```

As you can see, the nesting properties dont work correctly, it only works with the superior class, and everything else doesn`t appear in the ouput css.

Is there any solution actually for this problem?

Thanks!
