### ISSUE TITLE
Can't extend, if I import a sass file from within a class, because class is written twice in output... and again

### ISSUE THREAD

**Issue by donaldpipowitch** [sass/node-sass#239]
I have the following two sass files.

``` scss
// fileA.scss
.test-hello {
  color: red;
}

.test-world {
  @extend .test-hello;
}
```

``` scss
// fileB.scss
.theme {
   @import "fileA";
}
```

What I would expect, if I compile `fileB.scss`:

``` css
.theme .test-hello,
.theme .test-world {
  color: red;
}
```

What I get:

``` css
.theme .test-hello,
.theme .theme .test-world,
.theme .theme .test-world {
  color: red;
}
```

This happens for node-sass 0.8.1, [not in the original sass compiler](https://github.com/nex3/sass/issues/1101).
