### ISSUE TITLE
selector-unify fails when selector arg is generated by function

### ISSUE THREAD

**Issue by lunelson** [sass/node-sass#2420]
I've run in to a bug with `selector-unify`, where unifying a parent-selector with a function-generated selector causes a crash. The following repo shows the test case -- clone and run `npm t` -- I've noted in the file that it will compile if I don't generate the classes using a nested function.

https://github.com/lunelson/node-sass-selector-unify-test

```scss
@function base-class($base) {
  @return selector-parse('[class^="#{$base}-"], [class*=" #{$base}-"]');
}

// this output causes a crash
#{base-class('a')} {
  color: blue;
  & > * {
    @at-root #{selector-unify(&, base-class('b'))} {
      color: red;
    }
  }
}
```

```sh
- NPM version: 6.1.0
- Node version: 8.11.1
- Node Process:

{ http_parser: '2.8.0',
  node: '8.11.1',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

- Node Platform: darwin
- Node architecture: x64
- node-sass version:

node-sass       4.9.0   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]

- npm node-sass versions:
issue-node-sass-selector-unify
└── node-sass@4.9.0
```

**Comment by nschonni** [comment]
I'm not sure if this is already resolved, but per our issue template, can you file something with libsass? This would be solved there, rather than here, thanks!

**Comment by saper** [comment]
Test A renders with libsass 3.6.2 like this:

```css
.a {
  color: blue;
}

.a > .b {
  color: red;
}

```

Test B gives

```css
.a, .b {
  color: blue;
}

.a > .c, .a > .d, .b > .c, .b > .d {
  color: red;
}
```
