### ISSUE TITLE
If the SCSS variable value existt "\" then compiling it to CSS is empty.

### ISSUE THREAD

**Issue by peibinzhu** [sass/node-sass#2421]
RT,node-sass After compilation
SCSS: 
    $wb-var-dashboard: "\f101";
    i:before {
        content: $wb-var-dashboard;
    }
CSS:
  i:before { content: ""}
solve!

**Comment by nschonni** [comment]
Sorry, you didn't follow the issue template, so we can't help you.

**Comment by xzyfer** [comment]
SCSS
```scss
$wb-var-dashboard: "\f101";
i:before {
  content: $wb-var-dashboard;
}
```
CSS
```css
@charset "UTF-8";
i:before {
  content: "";
}
```
This is expected.
