### ISSUE TITLE
Terminal node-sass doesn't properly compile urls

### ISSUE THREAD

**Issue by manotoor** [sass/node-sass#2531]
- NPM version: 6.4.1
- Node version: 8.12.0
- Node Process:{ http_parser: '2.8.0',
  node: '8.12.0',
  v8: '6.2.414.66',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.0.2p',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }
- Node Platform: darwin
- Node architecture: x64
- node-sass version: node-sass	4.9.4	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
- npm node-sass versions: node-sass@4.9.4 

**node-sass -w default.scss /dist/default.css**

scss code: in _fonts.scss
```scss
@font-face {
    font-family: 'fira_sans';
    src: font-url('firasans-regular-webfont.eot');
    src: font-url('firasans-regular-webfont.eot?#iefix') format('embedded-opentype'),
         font-url('firasans-regular-webfont.woff2') format('woff2'),
         font-url('firasans-regular-webfont.woff') format('woff'),
         font-url('firasans-regular-webfont.ttf') format('truetype'),
         font-url('firasans-regular-webfont.svg#fira_sansregular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```
output code:
```css
@font-face {
  font-family: 'fira_sans';
  src: font-url("firasans-regular-webfont.eot");
  src: font-url("firasans-regular-webfont.eot?#iefix") format("embedded-opentype"), font-url("firasans-regular-webfont.woff2") format("woff2"), font-url("firasans-regular-webfont.woff") format("woff"), font-url("firasans-regular-webfont.ttf") format("truetype"), font-url("firasans-regular-webfont.svg#fira_sansregular") format("svg");
  font-weight: normal;
  font-style: normal; }
```
expected code:
```css
@font-face {
 font-family:'fira_sans';
 src:url('/font/firasans-regular-webfont.eot?1234567890');
 src:url('/font/firasans-regular-webfont.eot?&1234567890#iefix') format("embedded-opentype"),url('/font/firasans-regular-webfont.woff2?1234567890') format("woff2"),url('/font/firasans-regular-webfont.woff?1234567890') format("woff"),url('/font/firasans-regular-webfont.ttf?1234567890') format("truetype"),url('/font/firasans-regular-webfont.svg?1234567890#fira_sansregular') format("svg");
 font-weight:normal;
 font-style:normal
}
```
Folder path

```
   root
   |
   -precompile
    |
       --src(all scss files in here. and default imports fonts)
       --dist
   -compile
   |
      --font
      --img
      --devcss (linked to dist)
```
Seems as if no query is being fired to get the url. also happens with images
