### ISSUE TITLE
Compatibility @mixin has "};"

### ISSUE THREAD

**Issue by putaoshu** [sass/node-sass#254]
``` scss
    @mixin silly-links {
        a{
            color: blue;
            background-color: red;
        }
    };
```

"}" has ";" so report bug:

```
source string:6: error: invalid top-level expression
```

as we all know , "};" is error, but can you compatibility it, Thanks!
