### ISSUE TITLE
CSS variable can't have a "url..." content, which works in browser

### ISSUE THREAD

**Issue by radogado** [sass/node-sass#2577]
Hi,

I'm using this:

```scss
--chevron: url(data:image/svg+xml,%3C%3Fxml version='1.0' encoding='UTF-8'%3F%3E%3Csvg ver…8 0 16 16 0 16' fill='%23000' fill-rule='nonzero'/%3E%3C/g%3E%3C/svg%3E%0A);
    -webkit-mask: var(--chevron) center center no-repeat;
```

and it works in the browser as expected, but node-sass reports an error:

> Error: Invalid CSS after "		--chevron: ": expected "}", was "url("data:image..."

Any idea why? Thanks!

- NPM version (`npm -v`): 6.4.1
- Node version (`node -v`): v11.2.0
- Node Process (`node -p process.versions`): { http_parser: '2.8.0',
  node: '11.2.0',
  v8: '7.0.276.38-node.11',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.15.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '3',
  openssl: '1.1.0i',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' }
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`): node-sass	4.11.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
- npm node-sass versions (`npm ls node-sass`): node-sass@4.11.0

**Comment by nschonni** [comment]
The code you posted doesn't compile in any Sass version (Ruby, Libsass, or Dart). The following with a scope for the variable and quoting will work
```scss
:root {
  --chevron: "url(data:image/svg+xml,<?xml version='1.0' encoding='UTF-8'?><svg value='8 0 16 16 0 16' fill='#000' fill-rule='nonzero'/></g></svg>)";
}

.foo {
  -webkit-mask: var(--chevron) center center no-repeat;
}
```
