### ISSUE TITLE
:host(.class) compiles to just :host if class has a specific name

### ISSUE THREAD

**Issue by jhenninger** [sass/node-sass#2589]
This is a weird one. Compiling the following on Windows

```scss
:host {
  color: black;
}

:host(.inactive) {
  color: blue;
}

%placeholder {
  color: red;
}

.foo {
  @extend %placeholder;
}
```
results in
```css
:host {
  color: black; }

:host {
  color: blue; }

.foo {
  color: red; }
```

Where did the `.inactive` class go?

If you rename the class to something else you get the expected output: 
```scss
:host {
  color: black;
}

:host(.active) {
  color: blue;
}

%placeholder {
  color: red;
}

.foo {
  @extend %placeholder;
}
``` 
compiles to
```css
:host {
  color: black; }

:host(.active) {
  color: blue; }

.foo {
  color: red; }
```

Removing %placeholder` and `.foo` also "fixes" the problem:

```scss
:host {
  color: black;
}

:host(.inactive) {
  color: blue;
}
```

compiles to

```css
:host {
  color: black;
}

:host(.inactive) {
  color: blue;
}
```

I also tested this with SassC 3.4.9 and 3.5.4-7-gc0a6c (using precompiled binaries downloaded from http://libsass.ocbnet.ch/installer/) and problem does not occur. It also does not occur on Linux.

Version Info:
```powershell
> npm -v
6.5.0
> node -v
v11.9.0
> node -p process.versions
{ node: '11.9.0',
  v8: '7.0.276.38-node.16',
  uv: '1.25.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '67',
  nghttp2: '1.34.0',
  napi: '4',
  llhttp: '1.0.1',
  http_parser: '2.8.0',
  openssl: '1.1.1a',
  cldr: '34.0',
  icu: '63.1',
  tz: '2018e',
  unicode: '11.0' }
> node -p process.platform
win32
> node -p process.arch
x64
> node -p "require('node-sass').info"
node-sass       4.11.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
> npm ls node-sass
sasstest@1.0.0 C:\Users\Johannes\code\sasstest
`-- node-sass@4.11.0
```
