### ISSUE TITLE
German letter ß gets translated with extra space in content property

### ISSUE THREAD

**Issue by korsarNek** [sass/node-sass#2604]
When I use scss like this:
```scss
.my-element:before {
    content: 'Straße \A München';
    white-space: pre-line;
}
```

it gets translated to 
```css
.my-element:before {
  content: 'Stra\DF  e \A   M\FCnchen';
  white-space: pre-line;
}
```

There are two spaces after \DF, instead of one. Which means the word "Straße" shows up as "Straß e" with an extra space in the browser.

- NPM version 5.6.0
- Node version v10.0.0
- Node Process { http_parser: '2.8.0',
  node: '10.0.0',
  v8: '6.6.346.24-node.5',
  uv: '1.20.2',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
- Node Platform darwin
- Node architecture x64
- node-sass version
node-sass	4.11.0	(Wrapper)	[JavaScript]
libsass  	3.5.4	(Sass Compiler)	[C/C++]
- npm node-sass versions node-sass@4.11.0

When I paste the scss into https://www.sassmeister.com/ it doesn't show the extra spaces.
