### ISSUE TITLE
String Interpolation in Data Selectors

### ISSUE THREAD

**Issue by jhafner** [sass/node-sass#261]
When using the sass-rails gem (4.0.0), the following code:

``` scss
@for $i from 1 through 2 {
  [data-value="#{$i}"] {
    color: #fff
  }
}
```

...results in the following output:

``` css
[data-value="1"] { color: white; }

[data-value="2"] { color: white; }
```

However, when using the node-sass package (0.8.3) with grunt-sass (0.11.0), that same input results in the following output:

``` css
[data-value="#{$i}"] { color: #fff; }

[data-value="#{$i}"] {  color: #fff; }
```

The string interpolation is not happening in the data-value value...or am I doing something wrong?
