### ISSUE TITLE
Placeholder (%) Selectors still not compiling in 0.8.3

### ISSUE THREAD

**Issue by meandavejustice** [sass/node-sass#262]
Installed `0.8.3` from npm and ran against [css-modal](https://github.com/drublic/css-modal). Still isn't compiling Placeholder selectors properly.

Some sample output:

``` css
  @media screen and (max-height: 46em) and (min-width: 30em) {
    %modal %modal-fade, %modal .semantic-content {
      max-height: 340px;
      max-height: 50vh; } }
  @media screen and (max-height: 36em) and (min-width: 30em) {
    %modal %modal-fade, %modal .semantic-content {
      max-height: 265px;
      max-height: 40vh; } }

@media screen and (min-width: 30em) {
  %modal-fade {
    -webkit-transition: opacity 0.4s;
    -o-transition: opacity 0.4s;
    transition: opacity 0.4s; } }
```
