### ISSUE TITLE
@each directive examples fail with syntax error

### ISSUE THREAD

**Issue by jessepollak** [sass/node-sass#263]
If I try to run the following examples from the [SASS documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#each-directive), I get a syntax error.

``` scss
@each $animal, $color, $cursor in (puma, black, default),
                                  (sea-slug, blue, pointer),
                                  (egret, white, move) {
  .#{$animal}-icon {
    background-image: url('/images/#{$animal}.png');
    border: 2px solid $color;
    cursor: $cursor;
  }
}

@each $header, $size in (h1: 2em, h2: 1.5em, h3: 1.2em) {
  #{$header} {
    font-size: $size;
  }
}
```

``` bash
error: expected 'in' keyword in @each directive
```

Is this the correct place to open this issue or should I move it to libsass?
