### ISSUE TITLE
Quotes stop variable output

### ISSUE THREAD

**Issue by csi-lk** [sass/node-sass#275]
Using 0.8.4

I can't seem to figure out a way to output variables within quotes....

Pretty much if I output a variable within single or double quotes it will output it literally instead of outputting the variable, if I use the quote() function it will remove the quotes during output.

Unless i'm not seeing something blindingly obvious, i'd say this is a bug

Repro case:

Input

``` scss
$foo1: 'bus';
$foo2: 'car';
$foo3: 'plane';
$foo4: 'boat';
$foo5: 'train';
$foo6: 'tram';

[data-type="#{$foo1}"] {
  color: black;
}

[data-type='#{$foo2}'] {
  color: black;
}

[data-type=\'#{$foo3}\'] {
  color: black;
}

$foo4: quote($foo4);
[data-type=#{$foo4}] {
  color: black;
}

[data-type=#{quote($foo5)}] {
  color: black;
}

@function addquote($input) {
  @return quote($input);
}

[data-type=#{addquote($foo6)}] {
  color: black;
}
```

Output

``` css
[data-type="#{$foo1}"] {
  color: black; }

[data-type='#{$foo2}'] {
  color: black; }

[data-type=\'plane\'] {
  color: black; }

[data-type=boat] {
  color: black; }

[data-type=train] {
  color: black; }
```
