### ISSUE TITLE
SourceMap - Path in sources[] getting leading slash

### ISSUE THREAD

**Issue by am11** [sass/node-sass#276]
Consider the following command:

> node.exe node_modules\node-sass\bin\node-sass --source-map --output-style=expanded "C:\Users\Adeel\Documents\Visual Studio 2013\Projects\WebApplication1\WebApplication1\Content\sample.scss" --output "C:\Users\Adeel\Documents\Visual Studio 2013\Projects\WebApplication1\WebApplication1\Content\foo.css"

In `sample.scss`, I have:

``` scss
@import 'sample-import';

$bulb: blue;

.too {
    color: $bulb;
}
```

and `sample-import.scss`:

``` scss
.foo {
    color:red;
}
```

Both `sample.scss` and `sample-import.scss` are in same directory.

This is what I get in `sample.css.map`:

``` cmd
{"version":3,"file":"sample.css","sources":["sample.scss","/sample-import.scss"],"names":[],"mappings":"ACAA;EACI,OAAM;;ADGV;EACI,OAHG"}
```

Note the `/` before `sample-import.scss`. Ideally, since both are in same directory, it should be without leading slash. 

Is it by design?
