### ISSUE TITLE
Space before class-dot

### ISSUE THREAD

**Issue by Proximyst** [sass/node-sass#2803]
- NPM version (`npm -v`): 6.10.3
- Node version (`node -v`): 12.10.0
- Node Process (`node -p process.versions`):
```
{
  node: '12.10.0',
  v8: '7.6.303.29-node.16',
  uv: '1.31.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '72',
  nghttp2: '1.39.2',
  napi: '4',
  llhttp: '1.1.4',
  http_parser: '2.8.0',
  openssl: '1.1.1c',
  cldr: '35.1',
  icu: '64.2',
  tz: '2019a',
  unicode: '12.1'
}
```
- Node Platform (`node -p process.platform`): `win32`
- Node architecture (`node -p process.arch`): `x64`
- node-sass version (`node -p "require('node-sass').info"`):
```console
$ node-sass -v
node-sass       4.13.0  (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```
- npm node-sass versions (`npm ls node-sass`): ``-- node-sass@4.13.0`

With the following block:
```scss
div {
    width: 300px;
    height: 200px;
    background-color: red;
    padding: 5px;

    .matrix {
        // matrix(scaleX, skewY, skewX, scaleY, translateX, translateY)
        transform: matrix(1, 2, -1, 1, 80, 80);
    }
}
```

I get the following output with `--output-style=expanded`. This bug applies to all output-styles.
```css
div {
  width: 300px;
  height: 200px;
  background-color: red;
  padding: 5px;
}

div .matrix {
  transform: matrix(1, 2, -1, 1, 80, 80);
}

/*# sourceMappingURL=matrix.css.map */
```

A keen eye would spot the `div .matrix` which, at least on Firefox Quantum v72.0b4, doesn't actually apply the `matrix` class, as that's for any child. Sure, that might be the wanted behaviour in some situations, but in most, it's not. Is there a way to nest like this without having that problem?
