### ISSUE TITLE
@each multiple assignment not work

### ISSUE THREAD

**Issue by idealhack** [sass/node-sass#288]
from [sass doc](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#each-multi-assign)

code:

``` scss
@each $animal, $color, $cursor in (puma, black, default),
                                  (sea-slug, blue, pointer),
                                  (egret, white, move) {
  .#{$animal}-icon {
    background-image: url('/images/#{$animal}.png');
    border: 2px solid $color;
    cursor: $cursor;
  }
}
```

error:

```
error: expected 'in' keyword in @each directive
```
