### ISSUE TITLE
@function not work correctly

### ISSUE THREAD

**Issue by yutent** [sass/node-sass#2889]
scss source:

```scss
@function px($n: 1){
  @return ($n / 75) + rem
};

.foo { --size: px(75); margin: px(75); }
```

the result: 

```css
.foo { --size: px(75); margin: 1rem; }
```

expectation: 

```css
.foo { --size:  1rem; margin: 1rem; }
```
