### ISSUE TITLE
node-sass throws error while image path includes exclamation mark(!)

### ISSUE THREAD

**Issue by kingback** [sass/node-sass#3046]
- NPM version (`npm -v`): 6.14.6
- Node version (`node -v`): v12.18.3
- Node Process (`node -p process.versions`):
- Node Platform (`node -p process.platform`): darwin
- Node architecture (`node -p process.arch`): x64
- node-sass version (`node -p "require('node-sass').info"`):
  - node-sass       5.0.0   (Wrapper)       [JavaScript]
  - libsass         3.5.5   (Sass Compiler) [C/C++]
- npm node-sass versions (`npm ls node-sass`): 5.0.0

```css
.container {
  background: url(https://img.alicdn.com/imgextra/i1/O1CN01UGMWUI1kx5YpZyVz7_!!6000000004749-55-tps-42-43.svg);
}
```

![image](https://user-images.githubusercontent.com/471003/102449459-477f3a80-406f-11eb-80f0-18f8d0652759.png)

Wrap image path with `""` is ok.

```css
.container {
  background: url("https://img.alicdn.com/imgextra/i1/O1CN01UGMWUI1kx5YpZyVz7_!!6000000004749-55-tps-42-43.svg");
}
```
