### ISSUE TITLE
Functions the colors don't render

### ISSUE THREAD

**Issue by jamlfy** [sass/node-sass#307]
[Function colors](http://sass-lang.com/documentation/Sass/Script/Functions.html), in sass. For example
In the sass

``` scss
$color : #d0d;
.myClass {
   background : shade($color, 10%);
}
```

Render

``` css
.myClass {
   background : shade(#d0d, 10%);
}
```

Bat  in the documentation, the render

``` css
.myClass {
   background : #a6a6a;
}
```
