### ISSUE TITLE
Assertion failed: (handle->InternalFieldCount() > 0)....

### ISSUE THREAD

**Issue by jtangelder** [sass/node-sass#336]
Got this error on this simple scss file;

```
Assertion failed: (handle->InternalFieldCount() > 0), function Unwrap, file ../src/node_object_wrap.h, line 61.
```

``` scss
html, body {
  height: auto;
  position: relative;
  left: auto;
  top: auto;
  width: auto;
  overflow: auto;
  font-size: 9pt;
  line-height: 15pt;
  color: #000;
}

* {
  font-family: Arial, sans-serif;
}

h1, h2, h3, h4, h5, h6 {
  font-weight: bold;
}


.half{
  width: 49.5%;
  display: inline-block;
  vertical-align: top;
}
.third{
  width: 32%;
  display: inline-block;
  vertical-align: top;
}

.box{
  background: #fafafa;
  border: 1px solid #eee;
  padding: 1em;
}
.border-top{
  padding-top: 1em;
  border-top: 1px solid #eee;
}

em{
  text-transform: uppercase;
  font-style: normal;
  font-weight: bold;
  font-size: 12px;
}

// tables
table{
  width: 100%;
}

th, td{
  vertical-align: top;
  font-weight: normal;
}
tbody th{
  width: 30%;
  padding-right: 1em;
}


.col-sm-6{
  float: left;
}

.table-summary,
.section,
.legal,
tr{
  page-break-inside: avoid;
}

.section-title{
  page-break-after: avoid;
}
.section-break{
  page-break-after: avoid;
  margin-top: 30px;
}

// pdf
.pdf{
  .logo{
    width: 100px;
    float: right;
  }
}

.summary { font-size: 100%; }

.table-summary {
  background: none;

  tbody td,
  tbody th {
     border: 1px solid #ddd;
  }

  .text-price,
  .col-name { font-size: 15px; }
}

.table-minimal {
  &>tbody>tr>td,
  &>tbody>tr>th {
    color: #000;
    width: auto;
  }

  &>tbody>tr>th { font-weight: bold;color: #b4b4b4; }
}

```
