### ISSUE TITLE
node-sass wrong compiling?

### ISSUE THREAD

**Issue by frenz1e** [sass/node-sass#384]
``` scss
    .box em {
        text-decoration: underline;
    }
    .important {
        @extend .box;
     }
     .success {
         @extend .box;
     }
```

compiles to:

``` css
    .box em, .box .important, .box .success {
        text-decoration: underline; }
```

but, has to be:

``` css
    .box em, .important em, .success em {
        text-decoration: underline;
    }
```

*i'm using gulp-sass
