### ISSUE TITLE
mixins within silent extends fails

### ISSUE THREAD

**Issue by filipbech** [sass/node-sass#391]
If I have a mixin that takes content and use it inside a silent extend, the selector is not extended, it just outputs the silent selector. 
Check out this example! 

``` scss
@mixin mobileOnly() {
    @media all and (max-width: 568px) { 
        @content; 
    }
}

%test {
    color:#000;
    @include mobileOnly() {
        color:#fff;
    }
}

p {
    @extend %test;
}
```

in nodesass it returns

``` css
p {
  color: #000; }
  @media all and (max-width: 568px) {
    %test {
      color: #fff; } }
```

While it should return (which it does in ruby sass)

``` css
p {
  color: #000;
}
@media all and (max-width: 568px) {
  p {
    color: #fff;
  }
}
```
