### ISSUE TITLE
adding --outputStyle compressed leads to semantically different css

### ISSUE THREAD

**Issue by maxwellium** [sass/node-sass#433]
in a mixin

``` sass
@mixin flex($grow: 1, $shrink: null, $basis: null) {
  -webkit-box-flex: $grow;
  -webkit-flex: $grow $shrink $basis;
  -moz-box-flex: $grow;
  -moz-flex: $grow $shrink $basis;
  -ms-flex: $grow $shrink $basis;
  flex: $grow $shrink $basis;
}
```

the null params get parsed as they should producing this:

``` css
[flex] {
-webkit-flex: 1;
-moz-flex: 1;
-ms-flex: 1;
flex: 1;
}
```

when adding the outputStyle compressed flags however, the following output is returned

``` css
[flex] {
-webkit-flex: 1nullnull;
-moz-flex: 1nullnull;
-ms-flex: 1nullnull;
flex: 1nullnull;
}
```
