### ISSUE TITLE
Incorrect output for `@extend`

### ISSUE THREAD

**Issue by dfreeman** [sass/node-sass#459]
I'm seeing the output below for a simple usage of `@extend` on master. I originally assumed it was a bug in libsass (and I'm still guessing it is), but using sassc compiled against the same version (sass/libsass@9569ba1) gives correct output.

Input:

``` scss
.my-class a {
  font-weight: bold;
}

.my-class-extender {
  @extend .my-class;
}
```

Output from node-sass:

``` css
.my-class a, .my-class .my-class-extender {
  font-weight: bold; }
```

Output from sassc (and ruby-sass):

``` css
.my-class a, .my-class-extender a {
  font-weight: bold; }
```
