### ISSUE TITLE
@media doesn't get extended properly

### ISSUE THREAD

**Issue by erbridge** [sass/node-sass#460]
Input:

``` scss
.generic-thing {
  @media (max-width: 400px) {
    background-color: black;
  }
}

.specific-thing {
  width: 100px;
  @extend .generic-thing;
}

.other-specific-thing {
  @extend %generic-partial;
}
```

Expected output (something like):

``` css
@media (max-width: 400px) {
  .generic-thing {
    background-color: black; } }

.specific-thing {
  width: 100px; }
  @media (max-width: 400px) {
    .specific-thing {
      background-color: black; } }

@media (max-width: 400px) {
  .other-specific-thing {
    margin: 10px; } }
```

Actual output:

``` css
@media (max-width: 400px) {
  %generic-partial {
    margin: 10px; } }

@media (max-width: 400px) {
  .generic-thing {
    background-color: black; } }

.specific-thing {
  width: 100px; }
```
