### ISSUE TITLE
parsing error on @each with transform

### ISSUE THREAD

**Issue by jfroffice** [sass/node-sass#521]
``` scss
$my-transformation: (
    transform: scale3d(.8,.8,.8) rotate3d(0, 0, 1,90deg)
);

@each $property, $value in $my-transformation {
        #{$property} : #{$value};
}
```

lead to 'error reading values after transform'
