### ISSUE TITLE
@at-root doesn't work

### ISSUE THREAD

**Issue by dimitrinicolas** [sass/node-sass#559]
The function `@at-root` isn't supported

This feature is really useful especially in order to use this trick : [Declaring a CSS Animation @keyframes Directly on an Element using Sass](https://medium.com/@dtinth/declaring-a-css-animation-keyframes-directly-on-an-element-using-sass-f091a0a15dbd)

``` scss
@mixin animation-keyframes {
  $animation-number: 0 !default !global;
  $animation-number: $animation-number + 1 !global;
  $name: unquote("การเคลื่อนไหวที่-#{$animation-number}");
  animation-name: $name;
  @at-root {
    @keyframes #{$name} {
      @content;
    }
  }
}
```
