### ISSUE TITLE
px/em unit calculations outputting incorrect units.

### ISSUE THREAD

**Issue by browniefed** [sass/node-sass#585]
A few compass translations to raw scss have a hide-text mixin

``` css
@mixin hide-text($direction: $hide-text-direction) {
  @if $direction == left {
    $approximate-em-value: 12px / 1em;
    $wider-than-any-screen: -9999em;
    text-indent: $wider-than-any-screen * $approximate-em-value;
    overflow: hidden;
    text-align: left;
  } @else {
    // slightly wider than the box prevents issues with inline-block elements
    text-indent: 110%;
    white-space: nowrap;
    overflow: hidden;
  }
}
```

In 1.2.2 the calculation would return just the px unit like `-119988px` however in 2.0 beta the result is `-119988em*px/em`
