### ISSUE TITLE
@extend improperly works with nested selectors?

### ISSUE THREAD

**Issue by emirotin** [sass/node-sass#59]
``` scss
    .x {
        color: red;
        .y {
            color: blue;
        }
    }
    .z { @extends .x; }
```

compiles to

``` css
    .x, .z { color: red; }
    .x .y { color: blue; }
```

while it should be (as it works with Ruby Sass):

``` css
    .x, .z { color: red; }
    .x .y, .z .y { color: blue; }
```

I assume it's an issue with underlying libsass, but I'm not sure. Encountered this while porting some files from Ruby project to express project with mincer.
