### ISSUE TITLE
Cannot compile @keyframes

### ISSUE THREAD

**Issue by yefremov** [sass/node-sass#60]
I'm trying to compile following `.scss` but getting "undefined" as output

``` css
@mixin keyframes( $name )
{
    @keyframes $name {
        @content;
    }
}

@include keyframes( toggle )
{
    0% {
        height: 0%;
        width: 0%;
    }

    100% {
        height: 100%;
        width: 100%;
    }
}
```

is this related to `libsass`?
