### ISSUE TITLE
html data attribute is not working in sass file

### ISSUE THREAD

**Issue by rsjeyakumar** [sass/node-sass#613]
my below  [data-progress="#{$i}"] is not increment $i value ..i got as like it is.. it is considering as a string. 

 .loadingcontainer {
$i=1;
 @while ($i <= 2) {
        &[data-progress="#{$i}"] {
            .loading-inset .loading-inset__percentage:before {
                content: "#{$i}";
            }
        }

        $i : $i + 1;
    }
}

The final CSS output i got like below

 .loadingcontainer[data-progress="#{$i}"] {
            .loading-inset .loading-inset__percentage:before {
                content: "1";
            }
        }

 .loadingcontainer[data-progress="#{$i}"] {
            .loading-inset .loading-inset__percentage:before {
                content: "2";
            }
        }

**Comment by rsjeyakumar** [comment]
i am using "version": "0.9.0",

**Comment by am11** [comment]
Please test with latest version of node-sass, that is; v2.0.0-beta.

Going by your example:

```scss
.loadingcontainer {
  $i:1;
  @while ($i <= 2) {
    &[data-progress="#{$i}"] {
     .loading-inset .loading-inset__percentage:before {
       content: "#{$i}";
      }
    }
    $i : $i + 1;
  }
}
```

node-sass 2.0.0-beta output:

```css
.loadingcontainer[data-progress="1"] .loading-inset .loading-inset__percentage:before {
  content: "1"; }
.loadingcontainer[data-progress="2"] .loading-inset .loading-inset__percentage:before {
  content: "2"; }
```

Ruby sass v3.4.9 output:

```css
.loadingcontainer[data-progress="1"] .loading-inset .loading-inset__percentage:before {
  content: "1";
}
.loadingcontainer[data-progress="2"] .loading-inset .loading-inset__percentage:before {
  content: "2";
}
```
