### ISSUE TITLE
[bug]v1.2.3 *html output error

### ISSUE THREAD

**Issue by putaoshu** [sass/node-sass#634]
*html b{color:#333;}
*+html a{color:#666;}

use v1.2.3 output "stdin:1: invalid selector after *"

why? has options to handle it ?

**Comment by am11** [comment]
```scss
*html b{color:#333;}
*+html a{color:#666;}
```

is invalid. You need to add a space after `*` like so:

```scss
* html b{color:#333;}
*+html a{color:#666;}
```

@xzyfer, both ruby-sass and libsass allow `*+html` (without space) and convert it to `* +html` (implode whitespace) on compile, but throw on `*html`. I sense contradiction. Don't you? :)
