### ISSUE TITLE
segmentation fault when parsing invalid sass

### ISSUE THREAD

**Issue by mauritslamers** [sass/node-sass#7]
This is both a sort of proposal as well as an issue: 
If invalid css is being used, the module segfaults.

So proposal is to do a normal node-style callback with cb(err,result) and to catch the segfault in some way.

Example css used:

``` scss
$theme: 'ace';
$theme.checkbox {
  border: 0px none;

  &.disabled {
    opacity: .5;
  }
}
```
