### ISSUE TITLE
[Bug] Error: expected a variable name - with foundation scss since beta5

### ISSUE THREAD

**Issue by wzrdtales** [sass/node-sass#840]
Hello together,

Since node-sass@3.0.0-beta.5 the errors below occur, I have tested it with node-sass@3.0.0-beta.4 and everything works fine again.

    File: bower_components/foundation/scss/foundation/components/_forms.scss (335) expected a variable name (e.g. $x) or ')' for the parameter list for url

with the following content of this line:
```css
background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgeD0iMTJweCIgeT0iMHB4IiB3aWR0aD0iMjRweCIgaGVpZ2h0PSIzcHgiIHZpZXdCb3g9IjAgMCA2IDMiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDYgMyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+PHBvbHlnb24gcG9pbnRzPSI1Ljk5MiwwIDIuOTkyLDMgLTAuMDA4LDAgIi8+PC9zdmc+);
```

This seems to be a problem related to the commit
https://github.com/sass/libsass/commit/fd1814c58da94497142d929a5dd5be7c39d1ab70#diff-1c5f5dc7b5df73e7fb17abd6b3bd57d0

An upstream issue is already open here
https://github.com/sass/libsass/issues/1059

**Comment by mgreter** [comment]
IMO this is fixed with https://github.com/sass/libsass/pull/1051. Can you test?

**Comment by wzrdtales** [comment]
@mgreter Yes, this fixes this error.

But now another error occurs:

Build failed.
File: bower_components/foundation/scss/foundation/components/_forms.scss (366)
error reading values after $on


```css
// We use this mixin to turn on/off HTML5 number spinners
@mixin html5number($browser, $on:true) {
  @if $on==false {
      @if $browser==webkit {
        -webkit-appearance: none;
        margin: 0;
      } @else if $browser==moz {
        -moz-appearance: textfield;
      }
  }
}
```
