### ISSUE TITLE
SCSS being translated into a CSS with only "undefined"

### ISSUE THREAD

**Issue by danielquijada** [sass/node-sass#865]
I must say, I'm pretty new to this kind of development, and to this tool, so I might have a noobish mistake.

That said, my problem is:

* I have this in my app.coffee
```coffee
    srcPath = __dirname + '/sass'
    destPath = __dirname + '/public'
    app.use(sassMiddleware({
        src: srcPath,
        dest: destPath,
        debug: true,
        outputStyle: 'compressed',
    }));

    app.use(express.static(path.join( __dirname, 'public')));
```

* I also have a simple .scss file in my /sass directory:

```scss
    .message {
        border: 1px solid #ccc;
        padding: 10px;
        color: #333;
    }
```

just for testing purposes.

* When I request the .css files, they get generated, but they are all "undefined".

Is this a bug or am I doing something wrong? Thanks for your help :+1:
