### ISSUE TITLE
color: $variable compiling to color: variable, not color: value

### ISSUE THREAD

**Issue by jordinebot** [sass/node-sass#891]
I use variables with a color name when using a certain shade of any color and I noticed the following behaviour:

    $orange: #fc755f;
    a {
      border-bottom: 1px dotted $orange;
      &:hover {
        color: $orange;
        font-weight: normal;
        border-bottom: 1px solid $orange;
      }
    }

compiles to:

    a {
      border-bottom: 1px dotted #fc755f;
    }
    a:hover {
      color: orange;
      font-weight: normal;
      border-bottom: 1px solid #fc755f;
    }

So, in the property border (and others) $variable compiles to it's hex value but in (font) color it becomes just 'orange'. I understant I'm using a variable with a CSS preestablished color name, but anyway I think that shoudn't be the expected behaviour...

Anyone else is having this issue? Thank you!

**Comment by mgreter** [comment]
Unable to reproduce:
```css
a {
  border-bottom: 1px dotted #fc755f; }
  a:hover {
    color: #fc755f;
    font-weight: normal;
    border-bottom: 1px solid #fc755f; }
```
```
# psass -v
psass 0.4.0 (perl sass/scss compiler)
  libsass: 3.2.0-beta.6-4-g8963
  sass2scss: 1.0.3
```
