### ISSUE TITLE
Failure to compile media query with variable type

### ISSUE THREAD

**Issue by pfiaux** [sass/node-sass#90]
(again) Not sure if that's a node-sass issue or a libsass issue but the following code:

``` scss
/*
 * Media query,
 * Invalid issue
 */

$viewport: "only screen and (min-width: 700px)";

// Will not work
@media #{$viewport} {
  body {
    background: #3d3d3d;
  }
}
```

Will trigger:
`Warning: :9: error: invalid media query`
