### ISSUE TITLE
Classnames with escaped slashes are stated as invalid

### ISSUE THREAD

**Issue by Inkdpixels** [sass/node-sass#929]
Generating a class with an escaped slash in it's name will throw an error using node-sass 3.0.0 stable.

An example for such a classname would be
```css
$namespace: 'myNameSpace';
.#{$namespace}#{'-1\/1'} {
  width: 100%;
}
```

should result in 

```css
.myNameSpace-1\/1 {
  width: 100%;
}
```

but throws the error `invalid selector after .myNameSpace-1` after upgrading from node-sass 2.1.1 to 3.0.0.

Please note that escaping a slash in a className is completely valid in CSS and HTML, so it shouldn't throw an error in node-sass.

**Comment by mgreter** [comment]
Ruby sass has the same behavior, so node-sass/libsass is correct here (checked on sassmeister)!
You put an escaped backslash in a quoted string, so the escaping will be resolved when the string is unquoted. You either need to drop the quotes or double escape it!

**Comment by Inkdpixels** [comment]
Whelp! You're right. Solved it by modifying the code into:

```css
$namespace: 'myNameSpace';
.#{$namespace}-1#{\/}1 {
  width: 100%;
}
```

which works as expected. Thanks for the heads up @mgreter :+1:
