### ISSUE TITLE
Use of nth() on appended variable-length arglist never finishes compiling

### ISSUE THREAD

**Issue by davidkpiano** [sass/node-sass#930]
See below for issue:

```scss
@function foo($initial, $args...) {
    $args: append($args, 3);

    @return nth($args, 1);
}

@debug foo(1, 2);

// EXPECTED: 2

// ACTUAL (Ruby Sass v.3.4.13): 2
// ACTUAL (Node Sass v.3.0.0 and lower): << never finishes compiling, no output >>
```
