### ISSUE TITLE
Add a cache-buster option like Compass does

### ISSUE THREAD

**Issue by binarykitchen** [sass/node-sass#977]
These Compass URL helper functions are extremely useful and sorely missed in our project since we moved to SASS:
http://compass-style.org/reference/compass/helpers/urls/

Especially the cache busting, extremely useful and reduces many code lines in a gulp deployment script:

```
font-url($path, $only-path, $cache-buster) 
```

Any chance those util functions could be added? Or can these be implemented through SASS functions? Just kicking a discussion here ...

**Comment by xzyfer** [comment]
This library is not the right place for these functions. We support custom functions for this purpose.

This can be achieve this a simple Sass function. Something like the following (untested)

```scss
$base-path: "/my/path";
@function font-url($path, $only-path, $cache-buster) {
  @if $only-path {
    @return "#{$path}?#{$cache-buster}";
  } else {
    @return "#{base-path}/#{$path}?#{$cache-buster}";
  }
}
```
